const contacts = [
  {
    id: 1,
    name: "Martu",
    description: "It´s me, Johnny Guitar",
    avatar: "https://i.pravatar.cc/150?img=5",
    last_connection: "En linea",
    messages: [
      {
        emisor: "YO",
        hora: "23:10",
        id: 1,
        texto: "Holaa, estoy hablando con pepe!!",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "23:11",
        id: 2,
        texto: "ENSERIO?? A mi no me responde hace un montón",
      },
      {
        emisor: "OTRO",
        hora: "23:11",
        id: 3,
        texto: "Todo esta bien?",
      },
      {
        emisor: "YO",
        hora: "23:11",
        id: 4,
        texto: "Parece que le habian robado el celu",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "23:12",
        id: 5,
        texto: "Por eso no respondia seguro",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "23:15",
        id: 6,
        texto: "Uuu, que cagada, por eso no me respondia",
      },
      {
        emisor: "YO",
        hora: "23:16",
        id: 7,
        texto: "Vos que onda?",
        status: "no-visto",
      },
      {
        emisor: "YO",
        hora: "23:16",
        id: 8,
        texto: "No estabas enferma??",
        status: "no-visto",
      },
    ],
  },
  {
    id: 2,
    name: "Juani",
    description: "El amor puede mas",
    avatar: "https://i.pravatar.cc/150?img=3",
    last_connection: "Ult. vez hace 3 horas",
    messages: [
      {
        emisor: "YO",
        hora: "19:02",
        id: 1,
        texto: "Holaa, todo bienn?",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:08",
        id: 2,
        texto: "Bien por suerte, aca tomando mate",
      },
      {
        emisor: "OTRO",
        hora: "19:08",
        id: 3,
        texto: "Seguro me ponga a ver una peli o algo ahora",
      },
      {
        emisor: "OTRO",
        hora: "19:09",
        id: 4,
        texto: "Que onda que paso que me escribis??",
      },
      {
        emisor: "YO",
        hora: "19:11",
        id: 5,
        texto: "Uff, que ganas de un mate",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "19:11",
        id: 6,
        texto:
          "Nada te queria avisar que en 30 paso por tu casa para llevarte la compu",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:16",
        id: 7,
        texto: "No estas laburando vos?",
      },
      {
        emisor: "YO",
        hora: "19:21",
        id: 8,
        texto: "Sisi pero me largan antes hoy, por eso",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:22",
        id: 9,
        texto: "Bueno dale, aca te espero",
      },
      {
        emisor: "YO",
        hora: "19:22",
        id: 10,
        texto: "Genial!!",
        status: "visto",
      },
    ],
  },
  {
    id: 3,
    name: "Anita",
    description: "Quiero dormir",
    avatar: "https://i.pravatar.cc/150?img=16",
    last_connection: "Ult. vez hace 58 minutos",
    messages: [
      {
        emisor: "YO",
        hora: "17:36",
        id: 1,
        texto: "Sabes a quien me crucé el otro día",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "17:36",
        id: 2,
        texto: "No lo vas a poder creer",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "17:42",
        id: 3,
        texto: "A ver sorprendeme, a quien??",
      },
      {
        emisor: "YO",
        hora: "17:45",
        id: 4,
        texto: "A la nuestra compañera esa, la que gritaba siempre",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "17:45",
        id: 5,
        texto: "Te acoras?? Gritabapor todo jaja",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "17:47",
        id: 6,
        texto: "NOOOO JAJAJA",
      },
      {
        emisor: "OTRO",
        hora: "17:47",
        id: 7,
        texto: "ENSERIO???",
      },
      {
        emisor: "OTRO",
        hora: "17:47",
        id: 8,
        texto: "No me la bancaba a esa nono",
      },
      {
        emisor: "OTRO",
        hora: "17:48",
        id: 9,
        texto: "No porque gritaba, es que era muy falsa",
      },
      {
        emisor: "OTRO",
        hora: "17:48",
        id: 10,
        texto: "Por lo menos conmigo",
      },
      {
        emisor: "YO",
        hora: "17:49",
        id: 11,
        texto: "Posta? Conmigo era re buenita",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "17:49",
        id: 11,
        texto: "No me la imaginaba así",
        status: "no-visto",
      },
    ],
  },
  {
    id: 4,
    name: "Luchi",
    description: "Zzzz",
    avatar: "https://i.pravatar.cc/150?img=13",
    last_connection: "Ult. vez hace 1 hora",
    messages: [
      {
        emisor: "YO",
        hora: "16:01",
        id: 1,
        texto: "Che loco, cuando nos vamos a juntar?",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "16:37",
        id: 2,
        texto:
          "Vos sos el que no me dice nada hdp, vos sabes que puedo siempre",
      },
      {
        emisor: "YO",
        hora: "16:41",
        id: 3,
        texto: "Jajaja, bueno dale venite mañana",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "16:41",
        id: 4,
        texto: "Cocino algo a la noche solo si traes las bebidas",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "16:48",
        id: 5,
        texto: "Bueno dale, mañana te caigo",
      },
      {
        emisor: "OTRO",
        hora: "16:49",
        id: 6,
        texto: "Pero abrime rápido, siempre me dejas afuea como media hora",
      },
      {
        emisor: "OTRO",
        hora: "16:49",
        id: 7,
        texto: "Gil",
      },
      {
        emisor: "YO",
        hora: "16:51",
        id: 8,
        texto: "Naa cualquiera",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "16:51",
        id: 9,
        texto: "Ahora por mentiroso te dejo una hora afuera",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "16:56",
        id: 10,
        texto: "Andaaa, tomatelaa",
      },
    ],
  },
  {
    id: 5,
    name: "Sofiiii",
    description: "🌭=❤️",
    avatar: "https://i.pravatar.cc/150?img=10",
    last_connection: "Ult. vez hace 13 minutos",
    messages: [
      {
        emisor: "YO",
        hora: "15:20",
        id: 1,
        texto: "Che boluda, ¿fuiste a comprarle la comida al Cebolla?",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "15:22",
        id: 2,
        texto: "Naaa, me colgué mal. Pensé que ibas vos ",
      },
      {
        emisor: "YO",
        hora: "15:22",
        id: 3,
        texto: "¡Siempre lo mismo con vos eh! El gato ya me está mirando raro ",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "15:22",
        id: 4,
        texto:
          "Bueno bueno, voy ahora. ¿Cuál le compro? ¿La bolsita azul o la del pescadito?",
      },
      {
        emisor: "YO",
        hora: "15:22",
        id: 5,
        texto: "La azul, la del pescadito le cayó mal la otra vez ",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "15:27",
        id: 6,
        texto: "Jajaja pobre Cebolla. Ok, paso por el chino y la traigo",
      },
      {
        emisor: "YO",
        hora: "15:28",
        id: 7,
        texto:
          "De paso comprate algo para la merienda, tengo ganas de medialunas ",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "15:28",
        id: 8,
        texto: "Pero pagás vos que estoy seca eh",
      },
      {
        emisor: "YO",
        hora: "15:29",
        id: 9,
        texto: "Yo pagué la última, no te hagás la viva",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "15:32",
        id: 10,
        texto: "Mentiraaaa, fue la vez de las empanadas, contá bien",
      },
      {
        emisor: "YO",
        hora: "15:33",
        id: 11,
        texto: "Bueno, comprá 6 y te transfiero",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "15:35",
        id: 12,
        texto: "Dale, pero que haya de manteca",
      },
      {
        emisor: "YO",
        hora: "15:35",
        id: 13,
        texto:
          "Obvio. A Cebolla también le gustan esas pero no le vamos a dar ",
        status: "visto",
      },
    ],
  },
  {
    id: 6,
    name: "Carlos (Papá)",
    description: "Hola! Estoy usando WhatsApp",
    avatar: "https://i.pravatar.cc/150?img=6",
    last_connection: "Ult. vez hace 9 minutos",
    messages: [
      {
        emisor: "OTRO",
        hora: "11:56",
        id: 1,
        texto: "Ayer me di cuenta que no te habia escrito",
      },
      {
        emisor: "OTRO",
        hora: "11:56",
        id: 2,
        texto: "LLegue tarde a casa",
      },
      {
        emisor: "OTRO",
        hora: "11:57",
        id: 3,
        texto: "Tardo un monton el colectivo",
      },
      {
        emisor: "YO",
        hora: "12:03",
        id: 4,
        texto: "Tranqui, ni habia pensado en tu mensaje ",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "12:03",
        id: 5,
        texto: "Que era lo que me tenias que decir? ",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "12:05",
        id: 6,
        texto:
          "Te iba a decir que el sábado paso por tu casa a arreglarte el enchufe",
      },
      {
        emisor: "YO",
        hora: "12:06",
        id: 7,
        texto: "No puede ser el domingo? ",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "12:06",
        id: 8,
        texto: "El sabado tengo un cumple todo el día ",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "12:07",
        id: 9,
        texto: "Bueno, pero bien temprano a la mañana",
      },
      {
        emisor: "YO",
        hora: "12:12",
        id: 10,
        texto: "Que paja tan temprano, le voy a decir a Sofi que te abra ",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "12:24",
        id: 11,
        texto: "👍",
      },
    ],
  },
  {
    id: 7,
    name: "Laura (Facultad)",
    description: "Musica, baile y vida",
    avatar: "https://i.pravatar.cc/150?img=9",
    last_connection: "Ult. vez hace 1 hora",
    messages: [
      {
        emisor: "YO",
        hora: "11:30",
        id: 1,
        texto: "Euu me pasas lo apuntes de hoy porfa 🙏",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "11:31",
        id: 2,
        texto: "No pude ir hoy a la facu",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "11:43",
        id: 3,
        texto: "Dalee, ya te paso todo",
      },
      {
        emisor: "YO",
        hora: "11:45",
        id: 4,
        texto: "GRACIAS TE AMO, me salvaste posta",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "11:49",
        id: 5,
        texto: "📷Foto",
      },
      {
        emisor: "OTRO",
        hora: "11:49",
        id: 6,
        texto: "📷Foto",
      },
      {
        emisor: "OTRO",
        hora: "11:50",
        id: 7,
        texto: "📷Foto",
      },
      {
        emisor: "OTRO",
        hora: "11:51",
        id: 8,
        texto: "Si no entendes algo avisame amiga",
      },
      {
        emisor: "YO",
        hora: "11:53",
        id: 9,
        texto: "Dale, sos una genia",
        status: "no-visto",
      },
    ],
  },
  {
    id: 8,
    name: "Pedro (Facultad)",
    description: "Nunca subestimes a nadie",
    avatar: "https://i.pravatar.cc/150?img=7",
    last_connection: "Ult. vez hace 30 minutos",
    messages: [
      {
        emisor: "OTRO",
        hora: "10:24",
        id: 1,
        texto: "Que onda que faltaste hoy??",
      },
      {
        emisor: "YO",
        hora: "10:32",
        id: 2,
        texto: "Nada bld, el parcial del otro dia me mató mal",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "10:32",
        id: 3,
        texto: "Me quede estudiando en casa para el recuperatorio",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "10:33",
        id: 4,
        texto: "Uff, mepa que te voy a copiar mañana jaja",
      },
    ],
  },
  {
    id: 9,
    name: "Julian",
    description: "Si la vida te da limones, haz limonada",
    last_connection: "Ult. vez hace 12 horas",
    avatar: "https://i.pravatar.cc/150?img=11",
    messages: [
      {
        emisor: "OTRO",
        hora: "20:05",
        id: 1,
        texto: "Che, ¿por qué no me contestás? Estoy re mal sin vos.",
      },
      {
        emisor: "OTRO",
        hora: "20:05",
        id: 2,
        texto: "Te juro que puedo cambiar, aprendí un montón.",
      },
      {
        emisor: "OTRO",
        hora: "20:05",
        id: 3,
        texto: "Extraño hasta tus cagadas, posta que sos única.",
      },
      {
        emisor: "OTRO",
        hora: "20:05",
        id: 4,
        texto: "Dame una chance, no te vas a arrepentir.",
      },
      {
        emisor: "OTRO",
        hora: "20:05",
        id: 5,
        texto: "No puedo dormir, no como, solo pienso en vos.",
      },
      {
        emisor: "OTRO",
        hora: "20:5",
        id: 6,
        texto: "Vos y yo tenemos historia, no la tires a la basura.",
      },
      {
        emisor: "OTRO",
        hora: "20:06",
        id: 7,
        texto: "Por favor, contestame aunque sea para decir que no.",
      },
      {
        emisor: "OTRO",
        hora: "20:37",
        id: 8,
        texto: "Te prometo que esta vez voy a ser distinto, lo juro.",
      },
      {
        emisor: "YO",
        hora: "20:37",
        id: 9,
        texto: "Pará, ya te dije que no, basta.",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "20:37",
        id: 10,
        texto: "Pero no entendés, te necesito, sos todo para mí.",
      },
      {
        emisor: "OTRO",
        hora: "20:37",
        id: 11,
        texto: "Dejá que te demuestre que puedo cambiar de verdad.",
      },
      {
        emisor: "OTRO",
        hora: "20:38",
        id: 12,
        texto: "No quiero perderte, ni un segundo más sin vos.",
      },
      {
        emisor: "OTRO",
        hora: "20:38",
        id: 13,
        texto: "Por favor, dame aunque sea una oportunidad más.",
      },
      {
        emisor: "OTRO",
        hora: "20:38",
        id: 14,
        texto: "Si querés te espero el tiempo que haga falta, juro que sí.",
      },
    ],
  },
  {
    id: 10,
    name: "Gaby (Catering)",
    description: "Catering y servicios para eventos",
    avatar: "https://i.pravatar.cc/150?img=14",
    last_connection: "Ult. vez hace 2 horas",
    messages: [
      {
        emisor: "YO",
        hora: "19:07",
        id: 1,
        texto:
          "Hola, quería consultar sobre el catering para el cumple de mi hermano.",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "19:07",
        id: 2,
        texto: "Es para alrededor de 30 personas, entre chicos y adultos.",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:38",
        id: 3,
        texto:
          "¡Perfecto! Tenemos varias opciones. ¿Querés solo comida o también bebidas?",
      },
      {
        emisor: "YO",
        hora: "19:39",
        id: 4,
        texto:
          "Me interesa comida y algunas bebidas sin alcohol para los chicos.",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "19:39",
        id: 5,
        texto:
          "Mi hermano es fan de las pizzas, pero también quiero opciones para los adultos que prefieren algo más sano.",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:43",
        id: 6,
        texto:
          "Podemos armar una combinación de pizzas variadas y una ensalada fresca para los adultos.",
      },
      {
        emisor: "OTRO",
        hora: "19:43",
        id: 7,
        texto:
          "También tenemos opciones vegetarianas y sin gluten si les interesa.",
      },
      {
        emisor: "YO",
        hora: "19:45",
        id: 8,
        texto: "Genial, me interesa lo sin gluten para mi prima.",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "19:46",
        id: 9,
        texto: "¿Y qué opciones tienen para el postre?",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:49",
        id: 10,
        texto:
          "Tenemos tortas, cupcakes y helados. ¿Querés que te arme un paquete con todo eso?",
      },
      {
        emisor: "YO",
        hora: "19:53",
        id: 11,
        texto: "Sí, por favor. ¿Podés mandarme precios y detalles?",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:57",
        id: 12,
        texto: "Claro, te envío un presupuesto completo hoy a la tarde.",
      },
      {
        emisor: "OTRO",
        hora: "19:57",
        id: 13,
        texto:
          "También hacemos la entrega y montaje para que no tengas que preocuparte.",
      },
      {
        emisor: "YO",
        hora: "19:58",
        id: 14,
        texto: "Eso me viene bárbaro, gracias.",
        status: "visto",
      },
      {
        emisor: "YO",
        hora: "19:58",
        id: 15,
        texto: "¿Cuánto tiempo antes debería hacer la reserva?",
        status: "visto",
      },
      {
        emisor: "OTRO",
        hora: "19:59",
        id: 16,
        texto:
          "Con una semana de anticipación alcanza, pero mientras antes mejor.",
      },
      {
        emisor: "YO",
        hora: "20:00",
        id: 17,
        texto: "Perfecto, te espero el presupuesto entonces. ¡Gracias!",
        status: "visto",
      },
    ],
  },
];

const getContactList = () => {
  return contacts;
};

const getContactById = (contact_id) => {
  for (const contact of contacts) {
    if (Number(contact.id) === Number(contact_id)) {
      return contact;
    }
  }
  return null;
};

export { getContactList, getContactById };
export default contacts;
